AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

# Assignment Branch Condition size for initialize is too high
# Perceived complexity for deep_merge is too high
# Cyclomatic complexity for ... is too high
# Line is too long
# Method has too many lines
# ...
# (wtf)
Metrics:
  Enabled: false

# Do not introduce global variables
# (do want)
Style/GlobalVars:
  Enabled: false

# Missing space after #
# (debugging)
Style/LeadingCommentSpace:
  Enabled: false

# Redundant return detected
# (easy to read)
Style/RedundantReturn:
  Enabled: false

# Avoid comma after the last item of an array
# (do want)
Style/TrailingCommaInLiteral:
  Enabled: false
