language: ruby

gemfile:
  - Gemfile.devel

rvm:
  - 2.0
  - 2.2

script:
  - bundle exec rubocop
  - bundle exec rspec
  - bundle exec ruby -rminitest/autorun -Ilib:test -e 'Dir.glob "./test/*_test.rb", &method(:require)'
