---
swagger: "2.0"
info:
  version: "0.0.0"
  title: "Network Orchestrator API"
paths:
  /:
    get:
      summary: "Simple service check"
      description: "Simple service check. API version is returned."
      parameters: []
      responses:
        200:
          description: "OK, returns version"
          schema:
            type: "string"
        default:
          description: "KO"
          schema:
            type: "string"
  /network:
    get:
      summary: "Networks list"
      parameters:
        - in: "query"
          name: "user"
          description: "OpenNebula user identity"
          required: false
          type: "string"
      responses:
        200:
          description: "List existing networks"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Network"
        default:
          description: "KO"
          schema:
            type: "string"
  /network/{id}:
    get:
      summary: "Information about network"
      parameters:
        - in: "path"
          name: "id"
          description: "Network ID"
          required: true
          type: "integer"
          format: "int64"
        - in: "query"
          name: "user"
          description: "OpenNebula user identity"
          required: false
          type: "string"
      responses:
        200:
          description: "Get information about network"
          schema:
            $ref: "#/definitions/Network"
        default:
          description: "KO"
          schema:
            type: "string"
definitions:
  Range:
    description: "Address range"
    type: "object"
    required:
    - "address"
    properties:
      address:
        type: "string"
        description: "Address range (CIDR notation)"
      allocation:
        description: "Address allocation type (static, dynamic)"
        type: "string"
  Network:
    description: "Network object"
    type: "object"
    required:
    - "id"
    properties:
      id:
        description: "OpenNebula ID"
        type: "integer"
        format: "int64"
      title:
        description: "Network title"
        type: "string"
      description:
        description: "Network summary"
        type: "string"
      user:
        description: "Owner"
        type: "string"
      vlan:
        description: "VLAN ID"
        type: "integer"
        format: "int64"
      range:
        description: "IP address range"
        $ref: "#/definitions/Range"
      zone:
        description: "Availability zone (cluster)"
        type: "string"
