---
swagger: "2.0"
info:
  version: "0.0.0"
  title: "Network Orchestrator API"
paths:
  /:
    get:
      description: "Simple check"
      parameters: []
      responses:
        200:
          description: "OK, returns version"
          schema:
            type: "string"
        default:
          description: "KO"
          schema:
            type: "string"
  /list:
    get:
      parameters: []
      responses:
        200:
          description: "List existing networks"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Network"
        default:
          description: "KO"
          schema:
            type: "string"
  /network/{id}:
    get:
      parameters:
        - in: "path"
          name: "id"
          description: "Network ID"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "Get information about network"
          schema:
            $ref: "#/definitions/Network"
        default:
          description: "KO"
          schema:
            type: "string"
definitions:
  Network:
    type: "object"
    required:
    - "id"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      user:
        type: "string"
